name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  build:
    uses: itzg/github-workflows/.github/workflows/gradle-build.yml@main
